services:
  app:
    container_name: reward_dev
    image: reward-api-dev:1.0.0
    build:
      context: .
      dockerfile: ./Dockerfile
      target: development
    command: npm run start:debug
    ports:
      - 3000:${SERVER_PORT:-3000}
      - 9229:9229
    networks:
      - reward_server
    volumes:
      - .:/usr/src/app
      - node_modules:/usr/src/app/node_modules
    restart: unless-stopped
    depends_on:
      - db
      - phpmyadmin
  # Database
  db:
    image: mariadb:latest
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    ports:
      - '3361:3306'
    environment:
      MYSQL_ROOT_PASSWORD: ${REWARD_MYSQL_MASTER_PASS}
      MYSQL_DATABASE: ${REWARD_MYSQL_MASTER_DB}
      MYSQL_USER: ${REWARD_MYSQL_MASTER_USER}
      MYSQL_PASSWORD: ${REWARD_MYSQL_MASTER_PASS}
    networks:
      - reward_server
  # phpmyadmin
  phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - '8080:80'
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: ${REWARD_MYSQL_MASTER_PASS}
    networks:
      - reward_server
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - 22181:2181
    networks:
      - reward_server
  kafka:
    image: confluentinc/cp-kafka:latest
    depends_on:
      - zookeeper
    ports:
      - 29092:29092
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://cpl-kafka01.staging-bitcastle.work:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    networks:
      - reward_server
  c01:
     container_name: reward_c01_dev
     image: reward-api-dev:1.0.0
     build:
       context: .
       dockerfile: ./Dockerfile
       target: development
     command: npm run start:debug campaign01
     ports:
       - 3001:${SERVER_PORT:-3000}
     networks:
       - reward_server
     volumes:
       - .:/usr/src/app
       - node_modules:/usr/src/app/node_modules
     restart: unless-stopped
     depends_on:
       - db
networks:
  reward_server:
volumes:
  db_data:
  node_modules:
