services:
  app:
    container_name: reward_dev
    image: reward-api-dev:1.0.0
    build:
      context: .
      dockerfile: ./Dockerfile
      target: development
    command: npm run start:debug
    ports:
      - 3000:${SERVER_PORT:-3000}
      - 9229:9229
    networks:
      - reward_server
    volumes:
      - .:/usr/src/app
      - node_modules:/usr/src/app/node_modules
    restart: unless-stopped
    depends_on:
      - db
      - phpmyadmin
  # Database
  db:
    image: mariadb:latest
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    ports:
      - '3361:3306'
    environment:
      MYSQL_ROOT_PASSWORD: ${REWARD_MYSQL_MASTER_PASS}
      MYSQL_DATABASE: ${REWARD_MYSQL_MASTER_DB}
      MYSQL_USER: ${REWARD_MYSQL_MASTER_USER}
      MYSQL_PASSWORD: ${REWARD_MYSQL_MASTER_PASS}
    networks:
      - reward_server
  # phpmyadmin
  phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - '8080:80'
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: ${REWARD_MYSQL_MASTER_PASS}
    networks:
      - reward_server
  campaign01:
     container_name: reward_campaign01_dev
     image: reward-api-dev:1.0.0
     build:
       context: .
       dockerfile: ./Dockerfile
       target: development
     command: npm run start:debug campaign01
     ports:
       - 3001:${SERVER_PORT:-3000}
     networks:
       - reward_server
     volumes:
       - .:/usr/src/app
       - node_modules:/usr/src/app/node_modules
     restart: unless-stopped
     depends_on:
       - db
networks:
  reward_server:
volumes:
  db_data:
  node_modules:
